### ISSUE TITLE
Duplicate slack messages after each webhook

### ISSUE THREAD

**Issue by yob** [buildkite/statusbot#9]
After each webhook is received, we're seeing the full history of the incident re-posted into each channel.

The first webhook sends update A. The second webhook sends update A and B. The third webhook sends udpates A, B and C.

There's some errors on stderr that might be relevant:

![Screenshot from 2020-04-22 13-29-42](https://user-images.githubusercontent.com/8132/79975962-2ca7f680-84df-11ea-8c97-a07ceed34f0e.png)

Maybe there's an issue with our attempts to detect which updates have already been posted to a channel?

**Comment by lox** [comment]
Turns out this is due to Slack's fancy new WYSIWIG message types which don't work with the older slack library we are using.
